---
title: "입자계"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

</br>

## 비유로 본 기본 개념 {.unnumbered}

통계물리학은 아보가드로 수 $N_A \approx 6\times 10^{26}$ 정도의 입자 개수로 이루어진 시스템을 주로 다룬다. 이런 다수의 입자로 이루어진 시스템을 다루기 위해서 통계적인 방법을 사용하게 되는데, 통계 역학의 주요 개념들을 짚고 너어가기로 하자. 비유적으로 설명하기 위해 컵에 주사위 10개를 담아 테이블 위에 던지는 실험을 생각해 보기로 하자.


($1$) 계의 상태의 특정 : 각각의 실험의 결과를 서술하는 상세한 방법론이 필요하다. 10 개의 주사위 실험의 경우 각각에 대해 어떤 면이 위를 향하는지에 대한 특정이 필요하다.

($2$) 통계적 앙상블 : 이 실험은 본직적으로 결정론적지만 우리는 각각의 주사위에 대한 초기조건을 알고 있지 않은 경우가 많다. 이 경우 확률을 이용하게 된다. 즉 우리는 하나의 실험이 아니라 유사한 조건에서 여러번 수행된 10개의 주사위 도박의 앙상블(emssmble) 을 생각 할 수 있다. 또한 각각의 개별 실험의 결과는 다르지만 각각의 개별 실험 결과에 대한 확률을 생각 할 수 있다. 

($3$) 선험적 확률에 대한 기본 공리 : 이 실험의 경우 주사위의 6개의 면 각각이 위를 향할 확률이 모두 같다는 가정 혹은 공리가 필요하다. 이 공리는 선험적이며, 실험에 의해 그 확실성을 보장받을 수 있다.

($4$) 확률 계산 : 이 기본 공리를 인정한다면 확률 이론을 통해 이 주사위 던지기 실험의 결과에 대한 이론적 계산이 가능해진다.


</br>

## 계의 상태 

어떤 입자계라도 양자 역학의 법칙을 통해 기술 될 수 있다. 특히 계 전체를 기술하는 파동함수 $\psi (q_1,\ldots,\,q_f)$ 를 생각 할 수 있으며 파동함수의 독립변수가 $f$ 개 일 때 이 시스템의 **자유도 (degree of freedom)** 를 $f$ 이라고 한다. 즉 시스템의 상태는 $f$ 개의 값으로 특정된다. 또한 어떤 특정 시간 $t$ 에 시스템의 상태가 특정된다면, 과거와 미래 어떤 시간에 대해서도 시스템의 상태를 알 수 있다.

</br>

<div class="border" style="background-color:#F2F4F4  ;padding:5px;">

::: {#exm-part1_system_of_particles_1}

($1$) 위치가 고정된 단 하나의 입자로 이루어진 시스템을 생각하자. 이 입자의 스핀각운동량 $S=\frac{1}{2}\hbar$ 이다. 양자역학은 특정 방향에 대해 $m= \pm \frac{1}{2}$ 의 값을 가진다는 것을 알려준다. 

($2$) 이제 하나가 아닌 $N$ 개의 동일한 $S=\frac{1}{2}\hbar$ 입자로 이루어진 시스템을 생각하자. 역시 위치는 고정되어 있다고 하자. $i$ 번째 입자는 양자수 $m_i=\pm \frac{1}{2}\hbar$ 를 가질 수 있으므로 $m_1,\,m_2,\ldots, m_N$ 에 의해 시스템이 특정된다.

($3$) 동일한 1차원 단순조화진동자 $N$ 개 로 이루어진 시스템을 생각하자. 이 때 위치 좌표를 $x$ 라고 하자. 1차원 조화진동자는 에너지 양자수 $n$ 에 의해 결정된다는 것을 알고 있다. $i$ 번째 입자의 에너지 양자수를 $n_i$ 라고 하면 $n_1,\,n_2,\ldots,\, n_N$ 에 의해 시스템이 특정된다. 우리는 $n_i$ 가 $0$ 혹은 양의 정수의 값을 가진다는 것을 안다. 

($4$) 서로 약하게 상호작용하는 $N$ 개의 1차원 조화진동자로 이루어진 시스템을 생각하자. 

:::

</div>