project:
  type: book

book:
  title: "Statistical/Condesed Matter Physics"
  author: "Norah Jones"
  date: "7/18/2023"
  language: _language-ko_custom.yml

  chapters:
    - index.qmd
    - part : src/statistical/statistical.qmd
      chapters :
        - src/statistical/statistical_01.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    fontsize: 0.95em
    # html-math-method: mathml
  #  css: custom.css
  # pdf:
  #   documentclass: scrreprt



